/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingLiveRouteImport } from './routes/meeting.live'
import { Route as MeetingIdSummaryRouteImport } from './routes/meeting.$id.summary'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingLiveRoute = MeetingLiveRouteImport.update({
  id: '/meeting/live',
  path: '/meeting/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIdSummaryRoute = MeetingIdSummaryRouteImport.update({
  id: '/meeting/$id/summary',
  path: '/meeting/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/meeting/live': typeof MeetingLiveRoute
  '/meeting/$id/summary': typeof MeetingIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/meeting/live': typeof MeetingLiveRoute
  '/meeting/$id/summary': typeof MeetingIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/meeting/live': typeof MeetingLiveRoute
  '/meeting/$id/summary': typeof MeetingIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memory'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/meeting/live'
    | '/meeting/$id/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/memory'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/meeting/live'
    | '/meeting/$id/summary'
  id:
    | '__root__'
    | '/'
    | '/memory'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/meeting/live'
    | '/meeting/$id/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  MeetingLiveRoute: typeof MeetingLiveRoute
  MeetingIdSummaryRoute: typeof MeetingIdSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/live': {
      id: '/meeting/live'
      path: '/meeting/live'
      fullPath: '/meeting/live'
      preLoaderRoute: typeof MeetingLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$id/summary': {
      id: '/meeting/$id/summary'
      path: '/meeting/$id/summary'
      fullPath: '/meeting/$id/summary'
      preLoaderRoute: typeof MeetingIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  MeetingLiveRoute: MeetingLiveRoute,
  MeetingIdSummaryRoute: MeetingIdSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
